### ISSUE TITLE
Challenges Error

### ISSUE THREAD

**Issue by TheMattVid** [rlf/uSkyBlock#219]
I must have typed something wrong when editing my challenges. Uskyblock failed to load and I got this error: http://pastebin.com/QfUMGET2

Here's the challenges file: http://pastebin.com/J6AG0HMB

**Comment by rlf** [comment]
Make sure to quote any values, containing a `:`, i.e. displayItem in StrongLumberjack for one.

```yml
      StrongLumberjack:
        description: 'Collect wood from all kinds of trees.'
        type: onPlayer
        requiredItems: '17:0:32;+2 17:1:32;+2 17:2:32;+2 17:3:32;+2 162:0:32;+2 162:1:32;+2'
        displayItem: 17:2
```
