### ISSUE TITLE
Option to fix all worldguard regions based on island.yml and player.yml data

### ISSUE THREAD

**Issue by c0wg0d** [rlf/uSkyBlock#250]
We have a massive Skyblock world with hundreds of player islands, so this plugin is very important to us.  I modified our version to support WG6, and I setup our island region flags a lot differently than how they were originally.

Is there currently, or do you have plans to run some kind of audit/conversion on an existing world to fix all island problems?

We have many bugs and issues because of my sloppy fixes and I'd like to get them all working properly again without a lot of manual fixes (editing regions.yml by hand is scary).

**Comment by dutchy1001** [comment]
Due to your own modification it is hard to tell if our version will fix the things for you.
You can use the command "/usb island protectall" (with the use of our version v2.2-HF9b, unmodified) what will overwrite the region file in the Worldguard folder with the new format we added. This can take a while depending on the amount of islands. No garantie that it will fix or work in this case.
Out of curiosity which version did you modify?

**Comment by c0wg0d** [comment]
I modified the last version Talabrek released, which was V2.0.0.

I will gladly be a test subject for you now that you got Talabrek's blessing on this project. :)

As I said, Skyblock is extremely important to our server so I want to make sure it is working great, and new features would be wonderful!

I will setup a test server when I have time and report back.  Prepare for many incoming requests and bug reports! :)

**Comment by dutchy1001** [comment]
The update from v2.0.0 beta should not be a problem special when you going to try it out on a test server (I presume a copy of your live server) first. Aslong you use the dependencies.
Due to your own modifications you might get some errors that have to be manual fixed.

For the bug fixes, you will probably find out that many of the in v2.0.0 beta bugs have been fixed

**Comment by rlf** [comment]
The plugin will automatically re-create the wg-regions, using "the new" flags - when a player accesses his island.

That also means, that if you have a customized list of flags, those will be gone.
We have considered adding support for custom flags (and had at one time), but it introduced problems with the WG-support - we might be able to look into adding it again though.

**Comment by c0wg0d** [comment]
The only reason I changed the flags was because of how WG 6 changed everything to deny by default.

__global__ has priority 0 and build: DENY to prevent people building in between islands.

Every island has priority 100 and build -g MEMBERS: ALLOW, pvp: DENY, chest-access -g MEMBERS: ALLOW

That's all you need with WG6.

**Comment by dutchy1001** [comment]
The flag (build : deny) you added in the __global__ region is now by default added. The other flags you added should not be needed now. As (party) members are now added as owners to the region USB is sorting the rest what they can and cant do.
No need to add any other flag then.

**Comment by dutchy1001** [comment]
As no more comments are made I assume this issue has been solved (due to WG recreating new regions upon login).

**Comment by c0wg0d** [comment]
You can leave this bug as closed, but can you please tell me what the exact correct region setups are?

__global__ priority 0 build: deny
*island priority 100 with no flags?

And did region names change from eg. c0wg0disland to eg. 0,110island or is my server messed up?

**Comment by dutchy1001** [comment]
The region names did change a good while back from named to co-ords.

The Islandregion should look like this:
```
    -110,220island:
        min: {x: -162.0, y: 0.0, z: 168.0}
        max: {x: -58.0, y: 255.0, z: 272.0}
        members: {}
        flags: {entry: allow, greeting: §d** You are entering §bdutchy1001's §disland.,
            pvp: deny, farewell: §d** You are leaving §bdutchy1001's §disland.}
        owners:
            players: [dutchy1001]
        type: cuboid
        priority: 100
```
The Globalregion looks like:
```
    __global__:
        members: {}
        flags: {build: deny}
        owners: {}
        type: global
        priority: 0
```
