### ISSUE TITLE
World Guard player problem

### ISSUE THREAD

**Issue by pickledrange** [rlf/uSkyBlock#31]
Ive come across a weird problem. If a player that is console OP does not have an island (and subsequent world guard reigon) my 'Spawn' reigon is being overwritten and a new reigon created for the OP player.

Regular player joins game

[22:58:23] [User Authenticator #2/INFO]: UUID of player dannyevil is 702ec65f-7018-4bee-904b-cae39f9c27fa
[22:58:23] [Server thread/INFO]: Reloading player data!
[22:58:23] [Server thread/INFO]: Creating new player config!
[22:58:23] [Server thread/INFO]: Creating player config Paths!
[22:58:23] [Server thread/INFO]: Loaded player file for dannyevil
[22:58:24] [Server thread/INFO]: dannyevil[/64.234.31.140:61860] logged in with entity id 2770 at ([world] 3.5, 63.0, 2.5)
[22:58:24] [pool-12-thread-1/INFO]: Creating empty config: D:\Games\Minecraft\Server-1.8\plugins\Essentials\userdata\702ec65f-7018-4bee-904b-cae39f9c27fa.yml
[22:58:24] [Server thread/INFO]: [0;33;1mdannyevil joined the game.[m
[22:58:29] [Server thread/WARN]: dannyevil moved wrongly!

Console OP joins the game

[22:59:07] [Server thread/INFO]: CONSOLE: Opped dannyevil[m
[22:59:12] [Server thread/INFO]: dannyevil lost connection: Disconnected
[22:59:12] [Server thread/INFO]: Player data saved!
[22:59:12] [Server thread/INFO]: Removing player from memory: dannyevil
[22:59:18] [User Authenticator #3/INFO]: UUID of player dannyevil is 702ec65f-7018-4bee-904b-cae39f9c27fa
[22:59:18] [Server thread/INFO]: Reloading player data!
[22:59:18] [Server thread/INFO]: ©[uSkyBlock]&r Setting flag pvp to DENY for ALL
[22:59:18] [Server thread/INFO]: ©[uSkyBlock]&r Setting flag chest-access to DENY for ALL
[22:59:18] [Server thread/INFO]: ©[uSkyBlock]&r Setting flag use to DENY for ALL
[22:59:18] [Server thread/INFO]: ©[uSkyBlock]&r Setting flag destroy-vehicle to DENY for ALL
[22:59:18] [Server thread/INFO]: ©[uSkyBlock]&r Setting flag entity-item-frame-destroy to DENY for ALL
[22:59:18] [Server thread/INFO]: ©[uSkyBlock]&r Setting flag entity-painting-destroy to DENY for ALL
[22:59:18] [Server thread/INFO]: ©[uSkyBlock]&r Setting flag use to ALLOW for OWNERS
[22:59:18] [Server thread/INFO]: ©[uSkyBlock]&r Setting flag chest-access to ALLOW for OWNERS
[22:59:18] [Server thread/INFO]: New protected region created for dannyevil's Island by dannyevil
[22:59:18] [Server thread/INFO]: Loaded player file for dannyevil
[22:59:18] [Server thread/INFO]: dannyevil[/64.234.31.140:61912] logged in with entity id 2954 at ([skyworld] 0.7368222549480342, 176.0, 1.4036650512766893)

In WorldGuard Reigon.yml my spawn region, is replaced with a new region assigned to the OP

---
## THIS

```
spawn:
    min: {x: -208.0, y: 0.0, z: -208.0}
    max: {x: 207.0, y: 255.0, z: 207.0}
    members:
        unique-ids: [59f4777f-ac09-46f8-b760-ac7d0e088767, f77cd460-4a2c-487a-9689-6af1f6357d71,
            3feaed76-3cd5-4cfb-a1c7-07875e0f261b, 4e17b760-dd3a-40d5-9547-2643e8975511]
    flags:
        enderpearl: deny
        use: deny
        invincible: allow
        snow-fall: deny
        lighter: deny
        entity-painting-destroy: deny
        entity-item-frame-destroy: deny
        deny-spawn: [CREEPER, ZOMBIE, SLIME, SKELETON, CHICKEN, SHEEP, WITCH,
            ENDERMAN, SPIDER]
        mob-spawning: allow
        farewell: '&p** You are now leaving spawn'
    owners: {}
    type: cuboid
    priority: 0
```

---
## IS REPLACED WITH THIS

```
unwisedeadkillaisland:
    parent: __global__
    min: {x: -52.0, y: 0.0, z: -52.0}
    max: {x: 52.0, y: 255.0, z: 52.0}
    members: {}
    flags: {use: allow, greeting: §d** You are entering a protected island area. (UnwiseDeadkilla),
        destroy-vehicle: deny, chest-access: deny, entity-painting-destroy: deny,
        pvp: deny, entity-item-frame-destroy: deny, farewell: §d** You are leaving a protected island area. (UnwiseDeadkilla)}
    owners:
        players: [unwisedeadkilla]
    type: cuboid
    priority: 100
```
