### ISSUE TITLE
Creepers still do damage with creeper-explosion deny

### ISSUE THREAD

**Issue by c0wg0d** [rlf/uSkyBlock#348]
My players do not want any creeper damage, so I did:

/rg f __global__ creeper-damage deny

But they still destroy blocks.  Please provide a way to disable creeper damage in the config.

**Comment by dutchy1001** [comment]
That is because you have used the wrong flag, "creeper-damage" doesnt exist but should be "creeper-explosion". 

See [here](http://docs.enginehub.org/manual/worldguard/latest/regions/flags/) a full list of all the flags that can be used.

**Comment by c0wg0d** [comment]
It is creeper-explosion, my mistake.  It still does not work.

Region: __global__ (type=global, priority=0)
Flags: build: DENY, deny-spawn: [GHAST], creeper-explosion: DENY
Owners: (none)
Members: (none)
Bounds: (0,0,0) -> (0,0,0)

**Comment by dutchy1001** [comment]
when I look at my worldguard region file it looks like this 

```
    __global__:
        members: {}
        flags: {creeper-explosion: deny, build: deny}
        owners: {}
        type: global
        priority: 0
```

my flags are between brackets {} and no "bounds" are given. This might be due to the fact that it's from  an older WG. 
Adjust the region manual to the above format and do /wg reload. Let us know how you get on.

**Comment by c0wg0d** [comment]
Are you saying your WG is older or mine is?

>wg version
[12:46:05 INFO]: WorldGuard 6.0.0-beta-05.1569-

**Comment by dutchy1001** [comment]
no i didnt say that, it could be that your global region was made a while back with an older version, it just didnt update the format to what WG uses now.

**Comment by dutchy1001** [comment]
i just tested this on my test server, creepers do explode but no damage was done to blocks or player.

**Comment by c0wg0d** [comment]
I removed all flags on the __global__ region and then reset them.  Even after doing that, I still don't have the flags listed in my regions.yml file like you do.  They are not in curly braces.  I don't know if that matters or not.

I do not take player damage when a creeper blows up, but they are definitely still destroying blocks.

Do you have the protection: creepers: set to true in your uSkyblock config.yml?  Mine is true.

And do you have the /gamerule mobGriefing off set?  I do not because I still want enderman griefing and zombies to break doors.

**Comment by dutchy1001** [comment]
I'll have a look again, but i think i did test both ways, protection: creepers: true/false.

Have you tried just copy my `_global__` region into your file?

**Comment by c0wg0d** [comment]
Yes, I tried that also and it was the same result.

**Comment by dutchy1001** [comment]
I'll have to do a schoolrun first before i can test again.

**Comment by dutchy1001** [comment]
Ok retested this.

uSkyblock v2.3-HF2c (test version from git hub, nothing changed regarding the creeper explosion since the the last released version)
Worlguard v6.0.0-snapshot.1590 (this can be downloaded from the dev builds)
Using the default WG setting set by USB on creationof the skyworld:
```
    __global__:
        members: {}
        flags: {build: deny}
        owners: {}
        type: global
        priority: 0
```

First test with "protection/creepers: false"
Creeper explode doing block and player damage.

Second test with "protection/creepers: true"
Creeper grows big ready to explode but wont explode, moving away from the creeper let it go back to it's original size.

I added the flag "creeper-explosion: deny" with the command "/rg  f `__global__` creeper-explosion deny".
```
    __global__:
        members: {}
        flags: {creeper-explosion: deny, build: deny}
        owners: {}
        type: global
        priority: 0
```

Third test with "protection/creepers: false"
Creeper explode but no damage is done to block or player.

Fourth test with "protection/creepers: true"
Creeper grows big ready to explode but wont explode, moving away from the creeper let it go back to it's original size.(same as second test).
