### ISSUE TITLE
Challenge reward not correct after few times completing

### ISSUE THREAD

**Issue by dutchy1001** [rlf/uSkyBlock#362]
Challenge completing after the 4th time will not give the right amount repeat reward.

the challenge tested on was:
```
      caramba:
        description: "Il va faire tout vert."
        type: onPlayer
        requiredItems: '81:640'
        displayItem: '351:2'
        reward:
          text: "48 sables"
          items:  '12:48'
          currency: 150
          xp: 150
          commands:
          - 'console:effect {party} 1 60'
          - 'op:summon FireworksRocketEntity ~ ~ ~ {LifeTime:20}'
        repeatReward:
          text: "24 sables"
          items: '12:24'
          currency: 40
          xp: 40
```
From the 24 it should give normally as repeat reward  it only started to give 8 instead.

Usb v2.3-HF4c
All other plugins are up to date (but you knew that already)
