### ISSUE TITLE
Suggestion - Biome Shop and per-biome cooldowns

### ISSUE THREAD

**Issue by BlackBeltPanda** [rlf/uSkyBlock#499]
Would be cool to optionally require a fee to change an island's biome and to have per-biome cooldowns. If it's too cluttered for the main config, it could be a good idea to create a "biomes.yml" to store configuration settings for biomes, like prices, cooldown times, maybe even enable/disable specific biomes so they aren't displayed in the GUI.

**Comment by rlf** [comment]
We have been discussing "shops" now and then, but have so far decided against it.

But I agree, it does make sense, and as long as we hook into Vault, it should be no problem.
Only thing to consider is, to ensure players are in the skyworld when doing it.
And to allow it to be customized/disabled - for those who already have donor-shops configured.

**Comment by dutchy1001** [comment]
this can be created with ChestCommandGUI, see example below:

```yml
######################
#+                  +#
#   MENU SETTINGS    #
#+                  +#
######################

menu-settings:

  # name - appears as the title - REQUIRED
  name: '&9Biome Shop'

  # rows - the number of rows of the chest - REQUIRED
  rows: 3

  # command - OPTIONAL (you can remove this or set it to '')
  # Bind multiple commands using ; (command: 'menu; m; me')
  command: 'Biomeshop'

  # This command command will be execute when the menu is OPENed.
  # Supports all the icon command types.
  #OPEN-action: ''

  # OPEN-with-item - OPTIONAL
  # The menu will OPEN only right-clicking with orange wool [35:1]
  #OPEN-with-item:
  #  id: ''
  #  left-click: false
  #  right-click: true


######################
#+                  +#
#       ITEMS        #
#+                  +#
######################


sign-1:
  COMMAND: ''
  NAME: '&2 [p] Perks Shop Biomes [p]'
  LORE:
    - 'Click on an item to buy the biome'
    - 'listed in the item description.'
    - 'Biomes can only be changed once'
    - 'every hour. Anyone in the island'
    - 'group can change the island biome.'
  ID: SIGN
  KEEP-OPEN: true
  POSITION-X: 1
  POSITION-Y: 1


sign-2:
  COMMAND: 'island'
  NAME: '&6[arrow_left] Back to the SkyBlock menu'
  LORE:
    - '&eClick here to return to'
    - '&ethe main island screen'
  ID: nether_star
  KEEP-OPEN: true
  POSITION-X: 9
  POSITION-Y: 3


ocean:
  COMMAND: 'island biome ocean'
  NAME: '&fBiome: &6Ocean'
  LORE:
    - '&fCost: &2Free'
    - 'This will give access to the command'
    - '&e/island biome ocean &7to change your'
    - 'island to a ocean biome. Ocean biomes'
    - 'can spawn hostile mobs normally.'
  ID: '349:2'
  KEEP-OPEN: false
  POSITION-X: 2
  POSITION-Y: 1


plains:
  PRICE: 250
  COMMAND: 'console:pex user {player} add usb.biome.plains; island biome plains'
  NAME: '&fBiome: &6Plains'
  LORE:
    - '&fCost: &2250'
    - 'This will give access to the command'
    - '&e/island biome sky &7to change your'
    - 'island to The End biome. The End'
    - 'biome can only spawn enderman.'
  ID: LONG_GRASS:1
  KEEP-OPEN: false
  POSITION-X: 3
  POSITION-Y: 1


forest:
  PRICE: 250
  COMMAND: 'console:pex user {player} add usb.biome.forest; island biome forest'
  NAME: '&fBiome: &6Forest'
  LORE:
    - '&fCost: &2250'
    - 'This will give access to the command'
    - '&e/island biome forest &7to change your'
    - 'island to a forest biome. Forest biomes'
    - 'can spawn passive animals (and wolves).'
  ID: SAPLING:1
  KEEP-OPEN: false
  POSITION-X: 4
  POSITION-Y: 1


dessert:
  PRICE: 250
  COMMAND: 'console:pex user {player} add usb.biome.desert; island biome desert'
  NAME: '&fBiome: &6Desert'
  LORE:
    - '&fCost: &2250'
    - 'This will give access to the command'
    - '&e/island biome desert &7to change your'
    - 'island to a desert biome. Desert biomes'
    - 'do not have weather (rain/snow).'
  ID: SAND
  KEEP-OPEN: false
  POSITION-X: 5
  POSITION-Y: 1


jungle:
  PRICE: 300
  COMMAND: 'console:pex user {player} add usb.biome.jungle; island biome jungle'
  NAME: '&fBiome: &6Jungle'
  LORE:
    - '&fCost: &2300'
    - 'This will give access to the command'
    - '&e/island biome jungle &7to change your'
    - 'island to a jungle biome. Jungle biomes'
    - 'are bright and spawn ocelots.'
  ID: SAPLING:3
  KEEP-OPEN: false
  POSITION-X: 6
  POSITION-Y: 1


swampland:
  PRICE: 300
  COMMAND: 'console:pex user {player} add usb.biome.swampland; island biome swampland'
  NAME: '&fBiome: &6Swampland'
  LORE:
    - '&fCost: &2300'
    - 'This will give access to the command'
    - '&e/island biome swampland &7to change your'
    - 'island to a swampland biome. Swamps'
    - 'are dark and spawn slimes at night.'
  ID: WATER_LILY
  KEEP-OPEN: false
  POSITION-X: 7
  POSITION-Y: 1


taiga:
  PRICE: 300
  COMMAND: 'console:pex user {player} add usb.biome.tiaga; island biome tiaga'
  NAME: '&fBiome: &6Taiga(Snowy)'
  LORE:
    - '&fCost: &2300'
    - 'This will give access to the command'
    - '&e/island biome tiaga &7to change your'
    - 'island to a taiga biome. Tiaga biomes'
    - 'have snowfall and passive animals.'
  ID: snow_block
  KEEP-OPEN: false
  POSITION-X: 2
  POSITION-Y: 2


mushroom:
  PRICE: 400
  COMMAND: 'console:pex user {player} add usb.biome.mushroom; island biome mushroom'
  NAME: '&fBiome: &6Mushroom'
  LORE:
    - '&fCost: &2400'
    - 'This will give access to the command'
    - '&e/island biome mushroom &7to change your'
    - 'island to a mushroom biome. Mushroom'
    - 'biomes have no hostile mob spawns.'
  ID: RED_MUSHROOM
  KEEP-OPEN: false
  POSITION-X: 3
  POSITION-Y: 2


nether:
  PRICE: 500
  COMMAND: 'console:pex user {player} add usb.biome.hell; island biome hell'
  NAME: '&fBiome: &6Nether'
  LORE:
    - '&fCost: &2500'
    - 'This will give access to the command'
    - '&e/island biome hell &7to change your'
    - 'island to a nether biome. Nether'
    - 'biomes can spawn hostile mob.'
    - '(excluding Ghasts and blazes)'
  ID: 385
  KEEP-OPEN: false
  POSITION-X: 4
  POSITION-Y: 2


end:
  PRICE: 500
  COMMAND: 'console:pex user {player} add usb.biome.sky; island biome sky'
  NAME: '&fBiome: &6The End'
  LORE:
    - '&fCost: &2500'
    - 'This will give access to the command'
    - '&e/island biome sky &7to change your'
    - 'island to The End biome. The End'
    - 'biome can only spawn enderman.'
  ID: EYE_OF_ENDER
  KEEP-OPEN: false
  POSITION-X: 5
  POSITION-Y: 2


ehills:
  PRICE: 500
  COMMAND: 'console:pex user {player} add usb.biome.extreme_hills; island biome extreme_hills'
  NAME: '&fBiome: &6Extreme Hills'
  LORE:
    - '&fCost: &2500'
    - 'This will give access to the command'
    - '&e/island biome extreme_hills &7to change your'
    - 'island to Extreme Hills biome. The Extreme'
    - 'Hills biome can only spawn ??.'
  ID: EMERALD_ORE
  KEEP-OPEN: false
  POSITION-X: 6
  POSITION-Y: 2


docean:
  PRICE: 500
  COMMAND: 'console:pex user {player} add usb.biome.deep_ocean; island biome deep_ocean'
  NAME: '&fBiome: &6Deep Ocean'
  LORE:
    - '&fCost: &2500'
    - 'This will give access to the command'
    - '&e/island biome deep_ocean &7to change your'
    - 'island to Deep Ocean biome. The Deep'
    - 'Ocean biome can spawn guardians.'
  ID: prismarine_shard
  KEEP-OPEN: false
  POSITION-X: 7
  POSITION-Y: 2
```
This example is free to use but credit for this will be appreciated.

I will close this issue for now, if needed it can be reopened or a new issue can be made.
