### ISSUE TITLE
New Challenges Layout - Feature request

### ISSUE THREAD

**Issue by GiansCode** [rlf/uSkyBlock#514]
Hello there,

Since the challenge names cannot be upper case, I was wondering if it'd be possible to add something like this http://pastebin.com/kkkpkUNB - It just gives us more customisability

Thanks

**Comment by csorrows** [comment]
Pretty much the same idea as I had but without the code doing it for you. I really like this idea. The only issue is making users edit their existing challenges. Even though, the code could just auto fill the name field with the challenge name by default. Then it would just 'work' out of the box.

**Comment by rlf** [comment]
Good suggestion. And nice workaorund for the limitations of previous versions.

**Comment by csorrows** [comment]
It's all about input from the community. With the high level of coding skill you have, it makes the current environment a perfect storm.

**Comment by GiansCode** [comment]
Thanks!

Would also be nice if the broadcast message could have some JSON attributes. I guess we could always run the tellraw command, but, it'd be nice if it was included and handled by the plugin

**Comment by rlf** [comment]
Make a new request for that please - otherwise these issues get's to unfocused.

**Comment by csorrows** [comment]
Um yea, that was just a little quick to implement LOL.

**Comment by rlf** [comment]
Ye, I was slacking.. big time... :D

**Comment by voodootje0** [comment]
This new feature don't work 100%.
The rank displaynames works but the colors doesn't.
![image](https://cloud.githubusercontent.com/assets/6852308/10861307/213bec98-7f7b-11e5-8f5f-fe1dccc532b2.png)

The challange name doesn't work at all.
![image](https://cloud.githubusercontent.com/assets/6852308/10861331/a7adaf78-7f7b-11e5-86e8-76e720734472.png)
![image](https://cloud.githubusercontent.com/assets/6852308/10861332/b0df6672-7f7b-11e5-9b51-142c31ecb5d4.png)

**Comment by rlf** [comment]
I have to admit, this fix was done in between other tasks - so I didn't get around to testing it.

Will give it a swirl.

**Comment by csorrows** [comment]
Guess the first try *was* a little too fast.

**Comment by rlf** [comment]
even the 2nd try was too fast :D

**Comment by csorrows** [comment]
LOL

**Comment by rlf** [comment]
And... apparently the 3rd was bad too (the GUI can't complete challenges with new names).

**Comment by csorrows** [comment]
Keep grinding out the fails man! I'll still love ya.

**Comment by dutchy1001** [comment]
changing the challenge names works now including color codes

**Comment by dutchy1001** [comment]
the changes are working great, been testing this by creating a new challenges.yml
Format I use now is:
```
      defaultchallengename:
        name: '&a'
        description:
        type: onPlayer
#        type: islandLevel
#        type: onIsland
        requiredItems: ''
        repeatable: true
        displayItem:
#        tool:
#        resetInHours:
        takeItems: true
        reward:
          text:
          items:
          - ''
#          - ''
          permission: none
          currency: 0
          xp: 0
#          commands:
#          - op:
#          - console:
        repeatReward:
          text:
          items:
          - ''
#          - ''
          currency: 0
          xp: 0
#          commands:
#          - op:
#          - console:
```
