### ISSUE TITLE
Problem with levelConfig

### ISSUE THREAD

**Issue by Adam4CZ** [rlf/uSkyBlock#526]
Versions: 
![usb versions](https://cloud.githubusercontent.com/assets/15090021/10429808/7e921202-70fb-11e5-850e-8cb10ac1028a.png)

I have problem with this:
```-<num> - Is used to group different blocks together (for sharing limits or diminishing-returns).```

In wiki (https://github.com/rlf/uSkyBlock/wiki/levelConfig.yml) is an example, where I can count Acacia and Dark Oak Wood as "normal LOGs"
```yml
blockValues:
  # Give 20 pts. per LOG (naturally occurring wood)
  '17': 20
  # Count Acacia and Dark Oak as "normal LOGs".
  '162:*': -17
blockLimits:
  # Limit logs to only contribute to item-level for the first 20000 blocks. (Reg. of sub-type).
  '17': 20000
```

If I set Acacia and Dark Oak to <code>-17</code>, server will send errors to console when I type */is level*, */is info* etc. and my level/info it does not displayed.
So where is a mistake?
