### ISSUE TITLE
Open menu when interacting with X

### ISSUE THREAD

**Issue by rlf** [rlf/uSkyBlock#544]
Since we have this fine and nice GUI/Menu, it's a shame you have to type in a command to launch it.

I propose, that we open the main island menu, when a player LEFT clicks on a chest, within 10 blocks of the island center.

Any counter proposals?

**Comment by csorrows** [comment]
ale it a configurable block support custom blocks, and still allow /is to open it. Those are the additions I suggest.

**Comment by csorrows** [comment]
*Make it I meant. I'm posting th from my phone, I will clean it up when I get home. Sorry.

**Comment by rlf** [comment]
Perhaps even just make it a custom block within a sky-associated world then.
And make it configurable (on/off) as well.

**Comment by rlf** [comment]
... And now we are at it, perhaps make the command configurable as well...
So you can assign `/c` to a block if you like, or even `/c c cobblestonegenerator`.

**Comment by csorrows** [comment]
I thought about using a custom block or something but it wold always be in the way when building. Maybe just use the bedrock?

**Comment by rlf** [comment]
What about a "tool", i.e. assign it to an oak-sapling, and then when you hit a custom block with an oak-sapling, the menu opens (if configured).

Something like:
```
tool-menu:
  enabled: true
  tool: SAPLING
  commands:
    CHEST: island
    COBBLE: challenges complete cobblestonegenerator
    BED: c c homeowner
```
