### ISSUE TITLE
problem with renamed items and challenges

### ISSUE THREAD

**Issue by woolwind** [rlf/uSkyBlock#555]
This clearly isn't a skyblock issue, but I'm hoping you can help. I'm using an old plugin called itemrenamer to try to do some theme challenges.   It uses protocollib to change the names of things as they appear in inventory.  

So say I renamed netherwart to cranberries and created a cranberryfarmer challenge that requires 64 of item 372.  It nearly works.   If I have 2 netherwart and try to complete the challenge, it says I'm missign 62 Nether Stalk  (which is fine).   If I have 64 of them though, it says "You are missing 0 Nether Stalk"  and won't complete it.    If the challenge requires 32 of something, and I'm holding 64 of them, it tells me ' you are missing -32 whatsits'.     So somehow it both thinks I have the items but in a split-brained way it doesn't think so.  I'm hoping it is an easy fix, if you have a suggestion.

**Comment by rlf** [comment]
I need to get my hands dirty, using the plugins you use.
Could you provide a list of plugins and versions, perhaps even configuration, so I can try to reproduce it?

**Comment by csorrows** [comment]
I'm sure it's editing metadata which is why it is not recognized.

**Comment by rlf** [comment]
Most likely, but I need to see how the item-renamer messes with the item-stacks, if I'm going to have a chance of supporting it. Esp. since it shouldn't for instance use named items (named from an anvil) to complete challenges.

**Comment by woolwind** [comment]
ItemRenamer appears abandoned - I made some tweaks in order to compile for 1.8  Source code is in my fork. It needs more work to be clean (spits a lot of errors into server log)  but it is tough going, I need to know a lot more about NbtCompounds and suchlike than I do.    

The effect is not the same as anvil naming - those come out italicsized and renamed items. don't. 
 plugins and config here: http://pastebin.com/U8YyKaKu

the thing that will draw your eye is the config option stackrestrictor=true.  I tried setting it to false, but the result was unchanged.

thank you for looking at this, as I said I know it isn't really your problem. It would be really sweet if it worked though.

**Comment by woolwind** [comment]
unsurprisingly, commenting this out lets the challenge match on renamed stuff:
                ItemStack mat = new ItemStack(reqItem, amount, (short) subType);
               // ItemMeta meta = mat.getItemMeta();
               // meta.setDisplayName("\u00a7f" + amount + " " + VaultHandler.getItemName(mat));
               // mat.setItemMeta(meta);
                items.add(mat);

If I read it right, that code is there to let me create challenges requiring fancy items with lore on them? That's actually really cool but I can live without it in my event world that's only going to be up a couple weeks

**Comment by rlf** [comment]
The meta is set to `null` later, before testing against the inventory.

See https://github.com/rlf/uSkyBlock/blob/41fdc2a0ecfcc43ffff486460268c2634b94fc25/uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/challenge/ChallengeLogic.java#L290

So not sure why your above fix works.

**Comment by woolwind** [comment]
it is entirely possible it was sheer idiocy on my part brought on by too many trips through re-updating the challenges and what with there being two different item ids for netherwart stalks and seeds.

**Comment by woolwind** [comment]
After further testing it appears the change above does 2 things. It makes the renamed item matching work, and it makes the text after 'this challenge requires the following:' in the gui hoverover to go missing.

**Comment by woolwind** [comment]
Aha. this time I have it.  It is obvious that  containsAtLeast operates mysteriously differently than getCountOf as evidenced by the split-brained results I was getting. So - the following works for comparison:

           for (ItemStack required : requiredItems) {
                required.setItemMeta(null);
                /*
                if (!player.getInventory().containsAtLeast(required, required.getAmount())) {
                    sb.append(" \u00a74" + (required.getAmount() - getCountOf(player.getInventory(), required))
                            + " \u00a7b" + VaultHandler.getItemName(required));
                    hasAll = false;
                }*/
                
                if (getCountOf(player.getInventory(), required) < required.getAmount()) {
                    sb.append(" \u00a74" + (required.getAmount() - getCountOf(player.getInventory(), required))
                            + " \u00a7b" + VaultHandler.getItemName(required));
                    hasAll = false;
                }
                
            }
this command however, is ... cranky ...  it works sometimes and sometimes leaves the stuff:
  
 player.getInventory().removeItem(requiredItems.toArray(new ItemStack[requiredItems.size()]));

I've redone the challenge several times both as a first time and repeat and I can't yet find a pattern why it should work or not work.

**Comment by rlf** [comment]
`getCountOf` is a hack I made, that uses the `Material` + `durability` (aka subType aka data) of the `ItemStack` to count the actual numbers in the inventory.

Depending on how the ItemRenamer renames items, the line where we set the meta-data to `null` is most likely the one causing you grief. But, since we create the `ItemStack` directly, odds are, they won't match the items in the inventory - provided that the ItemRenamer actually changes stuff in the inventory.

For us to correctly support plugins as item-renamer, we probably need to support meta-data on items.

So the `containsAtLeast` and `removeItem` uses the "correct" ItemStack.

Either that, or we would have to write custom implementations of those two mentioned methods.

**Comment by rlf** [comment]
Should be possible, with the nbttag support in v2.7

**Comment by dutchy1001** [comment]
here is an example with a NBT tag reward:
```

    challenges:
      cobblestonegenerator:
        name: '&aCobble Stone Generator'
        description: Mine from a cobblestone generator.
        type: onPlayer
        requiredItems:
        - 4:64;+2
        repeatable: true
        displayItem: 1
        resetInHours: 12
        takeItems: true
        reward:
          text: 3 leather, 20% chance to get a book
          items:
          - '334:3'
          - 276:1 {display:{Name:"Dwarf Slayer",Lore:["Dawn of Elves"]},AttributeModifiers:[{AttributeName:"generic.maxHealth",Name:"generic.maxHealth",Amount:20,Operation:0,UUIDMost:48250,UUIDLeast:854890}],ench:[{id:16,lvl:5},{id:20,lvl:5},{id:34,lvl:3}]}
          - '{p=0.2}340:1'
          permission: none
          currency: 10
          xp: 10
          commands:
          - op:effect {player} regeneration
```
This only works is versions above v2.7 (which is still in ALPHA-pre-release state).
