### ISSUE TITLE
Challenge cooldown does not work

### ISSUE THREAD

**Issue by Adam4CZ** [rlf/uSkyBlock#556]
Versions: http://pastebin.com/raw.php?i=XxaGGxK1
Part of challenges.yml: http://pastebin.com/vi0APM2q
Part of permissions.yml:
```yml
groups:
  default:
    permissions:
    - modifyworld.*
    - usb.island.*
    - usb.party.*
    - essentials.spawn
    - essentials.list
```

If I complete challenges with cooldown (e.g. *applecollector*) without other permissions, cooldown does not work and I can complete challenge again and again. Maybe bug?
