### ISSUE TITLE
Issue with opening /is menu for a player with a plugin

### ISSUE THREAD

**Issue by i9hdkill** [rlf/uSkyBlock#687]
I have a small teleport menu with some options like teleport to the nether/merchants etc.
There is also a button that should open the /is  menu for a player.

It's via chestcommands 3.x. The button looks like this:
```
COMMAND: 'island'
  NAME: '&6&lDeine &aSkyblock&6 Insel!'
  LORE:
    - '&2Öffnet das &aSkyblock&2 Insel-Menü.'
  ID: 2
  POSITION-X: 1
  POSITION-Y: 1
```
If I put a "home" after "is", it works, but with just is or island it won't open the menu.

Before that I had a very old plugin named compassnavigation, this plugin was able to open the /is menu for a player.
Not sure if that's a uskyblock issue (the way how usky opens the is menu) or a chestcommands issue.

`Name: uSkyBlock
[01:55:26 INFO]: Version: 2.6.3
[01:55:26 INFO]: Description: Ultimate SkyBlock v2.6.3-38dff5-402
[01:55:26 INFO]: Language: en (en)
[01:55:26 INFO]: ------------------------------
[01:55:26 INFO]: Server: CraftBukkit git-Spigot-db6de12-930a59c (MC: 1.8.8)
[01:55:26 INFO]: ------------------------------
[01:55:26 INFO]: Vault 1.5.6-b49 (ENABLED)
[01:55:26 INFO]: WorldEdit 6.1.1-SNAPSHOT;3399-b19cd9be (ENABLED)
[01:55:26 INFO]: WorldGuard 6.1.1-SNAPSHOT.1628-e28b236 (ENABLED)
[01:55:26 INFO]: AsyncWorldEdit 3.3.0 (ENABLED)
[01:55:26 INFO]: Multiverse-Core 2.5-b711 (ENABLED)
[01:55:26 INFO]: ------------------------------
`

**Comment by dutchy1001** [comment]
you need to add 1 more line to the button config

```
COMMAND: 'island'
  NAME: '&6&lDeine &aSkyblock&6 Insel!'
  LORE:
    - '&2Öffnet das &aSkyblock&2 Insel-Menü.'
  ID: 2
  KEEP-OPEN: true
  POSITION-X: 1
  POSITION-Y: 1
```
