### ISSUE TITLE
Placeholder Issue

### ISSUE THREAD

**Issue by ItsShadowFang** [rlf/uSkyBlock#704]
Hey there guys,

Whenever I try to enable this "mvdwplaceholderapi: true" It causes an error and turns my config into an error config and then creates a completely new and fresh config. Any ideas on a way to fix this?

````
placeholder:

  # Hooks into MVdWPlaceholderAPI
  mvdwplaceholderapi: false

  # uSkyBlock native placeholders for chat messages and format
  chatplaceholder: false

  # uSkyBlock native placeholders for server-commands
  servercommandplaceholder: false
````
