### ISSUE TITLE
'challenge is not repeatable' error

### ISSUE THREAD

**Issue by woolwind** [rlf/uSkyBlock#710]
A player reported this for Lumberjack, and I just got it for ExpertFarmer.  I have not done the challenge at all yet, had all materials in hand, and got a message that the challenge isn't repeatable and I can't complete it.  I was able to complete Lumberjack twice, with not problem, so it isn't the challenge config, it moves.

**Comment by rlf** [comment]
Please share output from `/usb version` as well as your `challenges.yml` file (using pastebin).

**Comment by woolwind** [comment]
>usb version
[09:32:05 INFO]: Name: uSkyBlock
[09:32:05 INFO]: Version: 2.6.4
[09:32:05 INFO]: Description: Ultimate SkyBlock v2.6.4-bd1c2b-404
[09:32:05 INFO]: Language: en (en)
[09:32:05 INFO]: ------------------------------
[09:32:05 INFO]: Server: CraftBukkit git-Spigot-1480adb-8b61cc5 (MC: 1.9.2)
[09:32:05 INFO]: ------------------------------
[09:32:05 INFO]: Vault 1.5.6-b49 (ENABLED)
[09:32:05 INFO]: WorldEdit 6.1;no_git_id (ENABLED)
[09:32:05 INFO]: WorldGuard 6.1 (ENABLED)
[09:32:05 INFO]: Multiverse-Core 2.5-b678 (ENABLED)
[09:32:05 INFO]: Multiverse-NetherPortals 2.5-bUNKNOWN (ENABLED)
[09:32:05 INFO]: ------------------------------


I have not (yet) altered the default challenges file

**Comment by dutchy1001** [comment]
Could you check the challenges.yml to see if the "Lumberjack" challenge has set **repeatable: true**
See example:
```
lumberjack:
        name: '&aLumberjack'
        description: Collect all types of wood logs.
        type: onPlayer
        requiredItems: 17:0:16;+2 17:1:16;+2 17:2:16;+2 17:3:16;+2 162:0:16;+2 162:1:16;+2
        repeatable: true
        displayItem: 17
        takeItems: true
        reward:
          text: 4 redstone ore, 4 iron ore, 1 wolf
          items:
          - '73:4'
          - '15:4'
          permission: none
          currency: 30
          xp: 30
          commands:
          - 'console:give {player} minecraft:spawn_egg 1 0 {EntityTag:{id:"Wolf"}}'
        repeatReward:
          text: 1 redstone ore, 1 iron ore
          items:
          - '73:1'
          - '15:1'
          currency: 15
          xp: 15
```
If this is missing at your challenges.yml you can just add it as it is above.
