### ISSUE TITLE
Extra Party Size Permissions Doesn't Work

### ISSUE THREAD

**Issue by Denizay22** [rlf/uSkyBlock#780]
/usb v : http://prntscr.com/biax9k
Extra permissions in config file is here: http://pastebin.com/RECdPiCs

I'm using PEX for permissions
usb.extra.party1
usb.extra.party2
usb.extra.party3
This permissions doesn't work. It's still on 4 members.

**Comment by dutchy1001** [comment]
The way you added this to the config isn't the right way (close but not right)
To add extra party members copy the following to your config:
```
# This section allows donors to get specific perks
donor-perks:
  usb:
    perk:
      party5:
        maxPartySize: 5
      party6:
        maxPartySize: 6
      party7:
        maxPartySize: 7
      party8:
        maxPartySize: 8
```
The default party size is set to 4, so if you want to add 1 extra this will become 5 then etc. etc.

**Comment by rlf** [comment]
Dutchy means extra instead of perk in the section above.

**Comment by Denizay22** [comment]
Thanks :)

**Comment by dutchy1001** [comment]
They will both work aslong you start with **usb.**xxxx.xxxxx

**Comment by Denizay22** [comment]
I don't know what is wrong, but it's still not working.
Perks in config : http://pastebin.com/gmXbhd3r 
SS in config: http://prntscr.com/biqjw8

usb.perk.party1
usb.perk.party2
usb.perk.party3
This permissions doesn't work. (http://prntscr.com/biqkvv)

**Comment by dutchy1001** [comment]
you put in 1 to add an extra party member, as default is 4 to add an extra prty member you need to add this including the 4 from default. 
```
donor-perks:
  usb:
    perk:
      party1:
        maxPartySize: 5
      party2:
        maxPartySize: 6
      party3:
        maxPartySize: 7
```
as I did in my previous message
