### ISSUE TITLE
Challenge Item Id / Questions

### ISSUE THREAD

**Issue by Alibabaand40voleur** [rlf/uSkyBlock#802]
_Please paste the output from `/usb version` below_

![capture](https://cloud.githubusercontent.com/assets/18491206/16467990/31b327b0-3e4a-11e6-8979-ca6f6ac8b376.PNG)

This is my challenge :
``` 
      CoffreDesLimbes:
        name: '&aCoffre des limbes'
        description: Récolter des coffres des limbes.
        type: onPlayer
        requiredItems: '130:1:12'
        repeatable: true
        displayItem: 130
        takeItems: true
        reward:
          text: 6 Diamants, 2 Emeraude, 2 Larmes de ghast
          items:
          - '264:6'
          - '388:2'
          - '370:2'
          currency: 80
          xp: 80
        repeatReward:
          text: 4 Diamants, 2 Emeraude, 1 Larmes de ghast
          items:
          - '264:4'
          - '388:2'
          - '370:1'
          currency: 40
          xp: 40
```
And that what is get when i want compléte him : 
![enderchestbug](https://cloud.githubusercontent.com/assets/18491206/16468032/5335ae3a-3e4a-11e6-8802-779576911369.PNG)

Traduction : 

Essayer de compléter le challenge Coffres des limbes = Test to complete the challenge Ender Chest

Il vous manque les élements suivants : 12 ENDER_CHEST = U need to have the items : 12 ENDER_CHEST

Final traduction.

I think the bug is because is ender_chest and in the challenge is ENDER_CHEST.
Thx for ur help !
