### ISSUE TITLE
Challenges - Potions IDs as required items

### ISSUE THREAD

**Issue by MrFiliper** [rlf/uSkyBlock#804]
_Please paste the output from `/usb version` below_
```
Name: uSkyBlock
Version: 2.6.12
Description: Ultimate SkyBlock v2.6.12-9e2d30-413
Language: cs (cs)
------------------------------
Server: CraftBukkit git-Spigot-c3e4052-1953f52 (MC: 1.10)
------------------------------
Vault 1.5.6-b49 (ENABLED)
WorldEdit 6.1.3;7a097ca (ENABLED)
WorldGuard 6.1.2;e38d98d (ENABLED)
AsyncWorldEdit 2.2.2 (ENABLED)
Multiverse-Core 2.5-b717 (ENABLED)
Multiverse-NetherPortals 2.5-b675 (ENABLED)
------------------------------

In Minecraft version 1.10 was edited potions IDs. Potions now don´t have IDs. Is there any way to set potions in challenges? If not, you can add this thing?

**Comment by rlf** [comment]
Just use the `/give command` in the command section of rewards.

See http://minecraft.gamepedia.com/Potion

**Comment by dutchy1001** [comment]
when using potions in the challenges I get exactly what I put in using server 1.10.2 and client 1.10.2.
my test challenge is:
```

    challenges:
      cobblestonegenerator:
        name: '&aCobble Stone Generator'
        description: Mine from a cobblestone generator.
        type: onPlayer
        requiredItems: 4:64;+2
        repeatable: true
        displayItem: 1
        resetInHours: 12
        takeItems: true
        reward:
          text: 3 leather, 20% chance to get a book
          items:
          - '334:3'
          - '{p=0.2}340:1'
          - '373:819:5'
          permission: none
          currency: 10
          xp: 10
          commands:
          - op:effect {playername} 10
        repeatReward:
          text: 1 leather, 10% chance to get a book
          items:
          - '334:1'
          - '{p=0.1}340:1'
          currency: 5
          xp: 5
```
The potion used is **- '373:819:5'** which is "_Potion Of Fire Resistance II_"

**Comment by dutchy1001** [comment]
Edit: previous post deleted, used wrong potion description. 

when using potions in the challenges I get exactly what I put in using server 1.10.2 and client 1.10.2.
my test challenge is:
```
    challenges:
      cobblestonegenerator:
        name: '&aCobble Stone Generator'
        description: Mine from a cobblestone generator.
        type: onPlayer
        requiredItems: 4:64;+2
        repeatable: true
        displayItem: 1
        resetInHours: 12
        takeItems: true
        reward:
          text: 3 leather, 20% chance to get a book
          items:
          - '334:3'
          - '{p=0.2}340:1'
          - '373:8193:5'
          permission: none
          currency: 10
          xp: 10
          commands:
          - op:effect {playername} 10
        repeatReward:
          text: 1 leather, 10% chance to get a book
          items:
          - '334:1'
          - '{p=0.1}340:1'
          currency: 5
          xp: 5
```
The potion used is - '373:8193:5' which is "Potion Of Regeneration"
