### ISSUE TITLE
Default terra-forming for gravel creates dead-end

### ISSUE THREAD

**Issue by rlf** [rlf/uSkyBlock#818]
_Please paste the output from `/usb version` below_
```
https://ibin.co/2nMDXcfHbFLn.png
```

_What steps will reproduce the problem?_
1. Complete challenges until Nether Rank
2. Break your ONLY gravel
3. Get a flint-stone, and no gravel in return
4. Go weep in a corner

_Suggestion_
Let Sould Sand per default have a small chance of returning gravel as well

**Comment by dutchy1001** [comment]
after altering some of the value's the return is better then before, not sure this is the way as it could be abused.
```
  terraform:
    NETHERRACK:
    - '{p=0.7}NETHERRACK'
    - '{p=0.15}NETHERRACK'
    - '{p=0.05}QUARTZ_ORE'
    - '{p=0.05}SOUL_SAND'
    QUARTZ_ORE:
    - '{p=0.50}QUARTZ_ORE'
    - '{p=0.10}QUARTZ_ORE'
    SOUL_SAND:
    - '{p=0.70}SOUL_SAND'
    - '{p=0.10}SOUL_SAND'
    - '{p=0.35}GRAVEL'   (added)
    - '{p=0.15}GRAVEL'  (added)
    GRAVEL:
    - '{p=0.35}GRAVEL'  (adjusted)
    - '{p=0.10}GRAVEL'  (adjusted)
    - '{p=0.05}SOUL_SAND'
    GLOWSTONE:
    - '{p=0.85}GLOWSTONE'
    - '{p=0.15}GLOWSTONE'
```
if more servers can use these settings to see if they can be abused would be nice.

**Comment by rlf** [comment]
Could you update this with the latest values? Or make a pull-request?

**Comment by dutchy1001** [comment]
Will do when the changes I make are done. (prob tonight)

**Comment by rlf** [comment]
bump?

**Comment by dutchy1001** [comment]
this has been updated to the values we tested on our test server
```
  terraform:
    NETHERRACK:
    - '{p=0.7}NETHERRACK'
    - '{p=0.15}NETHERRACK'
    - '{p=0.05}QUARTZ_ORE'
    - '{p=0.05}SOUL_SAND'
    QUARTZ_ORE:
    - '{p=0.50}QUARTZ_ORE'
    - '{p=0.10}QUARTZ_ORE'
    SOUL_SAND:
    - '{p=0.70}SOUL_SAND'
    - '{p=0.10}SOUL_SAND'
    - '{p=0.05}GRAVEL'
    GRAVEL:
    - '{p=0.15}GRAVEL'
    - '{p=0.05}GRAVEL'
    - '{p=0.05}SOUL_SAND'
    GLOWSTONE:
    - '{p=0.85}GLOWSTONE'
    - '{p=0.15}GLOWSTONE'
```
