### ISSUE TITLE
Allow for non-terra-forming in nether

### ISSUE THREAD

**Issue by rlf** [rlf/uSkyBlock#820]
_Please paste the output from `/usb version` below_

```
2.7.2-alpha1
```

_What steps will reproduce the problem?_
1. Go to nether
2. Try to clear an area
3. Swear intensely and get aggrevated

_Suggestion_
Allow some way of disabling nether-terra-forming.
Perhaps require the right tool be used, or require at least stone/iron tools or something.

_If you have any log-files, please paste them to [pastebin.com](http://pastebin.com)_
- server-log: none

**Comment by rlf** [comment]
Suggestion A:
1. Only terra-form if the block-break contains drops (is mined with the right tool)
2. Allow for custom `weights` per tool-type. So slower tools gives more items.

I.e.
```yml
nether:
  enabled: true

  tool-multiplier:
    WOOD: 1.1 # Higher chance of extra-terraforming
    STONE: 1.0
    IRON: 0.8  # Lower chance
    GOLD: 0 # No terra-forming with gold tools
    DIAMOND: 0.2 # Only 20% chance
  # The probability of forming blocks
  terraform:
    NETHERRACK:
      - '{p=0.7}NETHERRACK'
      - '{p=0.15}NETHERRACK'
```
Meaning, if a `NETHERRACK` is broken with an `IRONPICK`, there's a `(0.7*0.8 =) 56%` chance of getting one netherrack.
