### ISSUE TITLE
Schematic merge issue

### ISSUE THREAD

**Issue by UnioDex** [rlf/uSkyBlock#864]
Hello i changed default schematics but default ones are adding to my schematic list.

Here my config:
```
  # name of the schematic
  Varsayilan:

    # permission needed to use island
    permission: usb.island.create

    # small discription of the island
    description: Varsayılan Skyblock adası

    # item to display in the GUI
    displayItem: SAPLING

    # optional, default true (true enabled in GUI, false disabled in GUI)
    enabled: true
  EskiStil:
    permission: usb.schematic.skysmp
    description: Eski stil Skyblock adası
    displayItem: GRASS
  VIP:
    permission: usb.schematic.vip
    description: VIP oyunculara özel Skyblock adası
    displayItem: GRASS
  UVIP:
    permission: usb.schematic.uvip
    description: UVIP oyunculara özel Skyblock adası
    displayItem: GRASS
```
But defaults are adding at last:
http://prntscr.com/cc0c2g
