### ISSUE TITLE
potions as requirement not working

### ISSUE THREAD

**Issue by dutchy1001** [rlf/uSkyBlock#866]
Using a potion for a requirement doesnt work. I have tried many different combinations but so far no luck.

**Comment by rlf** [comment]
Please post the output of `/usb version`, and provide a detailed description :facepunch: :hamster: :P

**Comment by dutchy1001** [comment]
Slapped around the ears for not using the proper issue report fields, bad bad dutchy

Name: uSkyBlock
Version: 2.7.3-alpha5
Ultimate SkyBlock v2.7.3-alpha5-576cd3-436[m
en_GB1 (en_GB1)
  State: d=256, r=128, i=68, p=196, n=true, awe=true
Server: Paper git-Paper-842 (MC: 1.10.2)
  State: online=true, bungee=true
Vault 1.5.6-b49
WorldEdit 6.1.4-SNAPSHOT;3609-9851099
WorldGuard 6.1.3-SNAPSHOT;1684-b2b0fe6
FastAsyncWorldEdit 16.08.22-3915881-230
Multiverse-Core 2.5.0-SNAPSHOT-b722
Multiverse-Portals 2.5.0-SNAPSHOT-b746 
Multiverse-NetherPortals 2.5.0-SNAPSHOT-b712

Trying to use potions in the requirements for challenges has been changed in the MC1.9/1.10 as the old format (373:8200:1) isn't working anymore. Some of the new formats I tried to use didn't had any success either
```minecraft:potion 1 0 {Potion:"minecraft:weakness"}```
```minecraft:potion 1 0 {Potion:"minecraft:8200"}```
```373:potion 1 0 {Potion:"minecraft:weakness"}```
```373:potion 1 0 {Potion:"minecraft:8200"}```
and probaly more formats but no luck.
When using the give command in the command section for the rewards given for a challenge is working fine with the following format:
```give [player] minecraft:potion 1 0 {Potion:"minecraft:weakness"}```

**Comment by rlf** [comment]
Please share (an extract) of your challenges.yml file (pastebin)

**Comment by dutchy1001** [comment]
An extract of the challenges file can be found [here](https://github.com/rlf/uSkyBlock/blob/master/uSkyBlock-Core/src/main/resources/challenges.yml)

**Comment by rlf** [comment]
Huh? No potions in that challenge file is there?

**Comment by dutchy1001** [comment]
This format will show the requirement in the challenges GUI but when trying to complete it ignores the "weakness" (8200) potion even when you have it in your inventory.
```
      cobblestonegenerator:
        name: '&7Cobble Stone Generator'
        description: Mine from a cobblestone generator.
        type: onPlayer
        requiredItems:
        - '4:64;+2'
        - '373:8200:2;+2'
        displayItem: COBBLESTONE
        lockedDisplayItem: STAINED_GLASS_PANE:7
        resetInHours: 12
        reward:
          text: 3 leather, 20% chance to get a book
          items:
          - '334:3'
          - '{p=0.2}340:1'
```
When getting the NBTtag it gives the following:
`info for: 373:1`
`name: Potion`
`NBTtag: {Potion:"minecraft:weakness"}`

No matter how I use the NBT format it will not show as a requirement in the challenges GUI nor will it require the potion to complete the challenge (the following will have a few examples I tried).

```
      cobblestonegenerator:
        name: '&7Cobble Stone Generator'
        description: Mine from a cobblestone generator.
        type: onPlayer
        requiredItems:
        - '4:64;+2'
        - '{Potion:"minecraft:weakness"}'
        - '{Potion:"minecraft:weakness"}:1'
        - '373:1 {Potion:"minecraft:weakness"}'
        - 'minecraft:Potion {Potion:"minecraft:weakness"}'
        - 'minecraft:Potion {Potion:"minecraft:weakness"}:1'
        displayItem: COBBLESTONE
        lockedDisplayItem: STAINED_GLASS_PANE:7
        resetInHours: 12
        reward:
          text: 3 leather, 20% chance to get a book
          items:
          - '334:3'
          - '{p=0.2}340:1'
```
none of the above examples work or show in the challenges GUI.
