### ISSUE TITLE
"Could not pass PlayerMoveEvent" NullPointerException Spam

### ISSUE THREAD

**Issue by BlackBeltPanda** [rlf/uSkyBlock#934]
_Please paste the output from `/usb version` below_
```
Name: uSkyBlock
Version: 2.7.3-alpha9
Description: Ultimate SkyBlock v2.7.3-alpha9-0d8854-444
Language: en (en)
State: d=500, r=152, i=3,496, p=12,456, n=false, awe=true
Server: Paper git-Paper-908 (MC: 1.10.2)
State: online=true, bungee=true
------------------------------
Vault 1.5.6-b49 (ENABLED)
WorldEdit 6.1.3;7a097ca (ENABLED)
WorldGuard 6.1.2;e38d98d (ENABLED)
FastAsyncWorldEdit 16.11.17-e16bcae-372-9.11.4 (ENABLED)
Multiverse-Core 2.5-b719 (ENABLED)
Multiverse-NetherPortals 2.5-b710 (ENABLED)
------------------------------
```

_What steps will reproduce the problem?_
The errors began after a player, FantasySurvival, logged into the server. Their USB player file contains their old username; not sure if that's the problem.

_If you have any log-files, please paste them to [pastebin.com](http://pastebin.com)_
* server-log: http://pastebin.com/raw/xumXWHg4
* FantasySurvival's USB player file: http://pastebin.com/raw/BhV0EGPy
* FantasySurvival's Island file: http://pastebin.com/raw/mWR9x05G

Edit:
This may be an issue related to a player changing their name to the same name another player had. Looking at the uuid2name.yml file, I see an entry for "i_dogaming998":
```
47e2b843-2f8c-3c86-98c8-6fff3a1f3826:
  name: i_dogaming998
  updated: 1472267115225
  displayName: i_dogaming998
```
The entry for FantasySurvival, formerly "I_DoGaming998", appears as:
```
b0a70f85-4731-40d1-9f98-8bcd50a50f53:
  name: FantasySurvival
  updated: 1479605259691
  displayName: FantasySurvival
  aka:
  - Best_MC_Gamer
  - I_Rule_Survivals
  - I_Love_SkyBlock
```
Edit 2:
The first UUID, for "i_dogaming998", doesn't appear to be valid. It seems somewhere along the line USB retrieved the incorrect UUID for the player.

Edit 3: Manually updating FantasySurvival's USB player file with their new username, adding "I_DoGaming998" to "FantasySurvival"'s "aka" section, and removing the invalid UUID entry for "i_dogaming998" didn't help. There's no USB player file for the invalid UUID.

Edit 4: There were more sections with invalid UUIDs containing FantasySurvival's old usernames.
```
1efff614-54c5-30f7-9e00-2dd40171a7d9:
name: I_Love_skyblock
updated: 1477532003745
displayName: I_Love_skyblock
```
```
87dc0ac0-57b2-3f73-b8b1-942d29fe7131: I_Love_SkyBlockk
```
Removing those entries also did not fix the problem.

**Comment by BlackBeltPanda** [comment]
Update:
This may be an issue related to a player changing their name to the same name another player had. Looking at the uuid2name.yml file, I see an entry for "i_dogaming998":
```
47e2b843-2f8c-3c86-98c8-6fff3a1f3826:
  name: i_dogaming998
  updated: 1472267115225
  displayName: i_dogaming998
```
The entry for FantasySurvival, formerly "I_DoGaming998", appears as:
```
b0a70f85-4731-40d1-9f98-8bcd50a50f53:
  name: FantasySurvival
  updated: 1479605259691
  displayName: FantasySurvival
  aka:
  - Best_MC_Gamer
  - I_Rule_Survivals
  - I_Love_SkyBlock
```
